---
- name: Load image from archive and push to a private registry
  copy:
    src: dtr_images_2.4.6.tar.gz
    dest: /tmp/dtr_images_2.4.6.tar.gz

- name: Load images
  shell: docker load < /tmp/dtr_images_2.4.6.tar.gz

- name: rpm | Configure the Docker engine
  template:
    src: config.j2
    dest: "{{docker_config}}"
  notify: restart docker-engine
